api:
  image: node:0.12
  container_name: api-server
  command: npm start
  volumes:
    - ./api-server:/api-server
  working_dir: /api-server
  ports:
    - "7000:3000"
  links:
    - db
  environment:
    - API_PORT=3000
db:
  image: mongo
  container_name: mongodb
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
