api:
  image: node:0.12
  container_name: api-server
  command: npm start
  volumes:
    - ./api-server:/api-server
  working_dir: /api-server
  ports:
    - "7000:3000"
  links:
    - mongodb
  environment:
    - API_PORT=3000
    - MONGODB_USERNAME=mongo
    - MONGODB_PASSWORD=mongo
    - MONGODB_PORT=27017
mongodb:
  image: mongo
  container_name: mongodb
  expose:
    - "27017" 
  volumes:
    - ./datadb:/data/db
  environment:
    - MONGODB_USERNAME=mongo
    - MONGODB_PASSWORD=mongo
  command: "--smallfiles --logpath=/data/db/logs"
